name: Spring CI

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Build and run Docker Compose
        run: |
          docker-compose up -d
          docker image prune -f

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: project-artifacts
          path: |
            build/libs/*.jar  

      - name: Docker Hub Login
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
            docker build -t youngkyonyou/aio:latest .
      - name: Push Docker Image
        run: |
            docker push youngkyonyou/aio:latest